language: python
python:
  - '3.8'
  - '3.7'
  - '3.6'
install:
  - |
    pip3 install codecov
    pip3 install -r requirements.txt
script:
  - coverage run -m unittest discover tests/
after_success:
  - codecov
